#include <memory>     // std::unique_ptr
#include <chrono>     // std::chrono
#include <complex>    // std::complex
#include <cmath>      // std::cos, sin, sqrt, exp
#include <algorithm>  // std::max
#include <vector>     // std::vector
#include <iostream>   // std::cout, cerr
#include <cstdint>    // uint32_t, uint64_t
#include <opencv2/core.hpp>
#define _USE_MATH_DEFINES
#include <cmath>
using namespace std;
// C ABI bridge (Rust <-> C++)
// These are generated by cbindgen from the Rust backend.
#ifdef HAVE_WGPU_BACKEND
extern "C"
{
  void * sonar_wgpu_create(
    uint32_t n_beams, uint32_t n_rays, uint32_t n_freq,
    float sound_speed, float bandwidth,
    float max_range, float attenuation,
    float source_level, float sensor_gain,
    float h_fov, float v_fov,
    uint64_t seed);

  float * sonar_wgpu_compute(
    void * engine,
    const float * depth,
    const float * normals,
    const float * refl,
    const float * beam_corr,
    uint32_t n_beams, uint32_t n_rays, uint32_t n_freq,
    uint64_t frame,
    float beam_corr_sum);

  void sonar_wgpu_free(float * ptr, size_t len);
  void sonar_wgpu_destroy(void * engine);
}   
#endif

namespace gz
{
namespace sensors
{


// CPU backend (reference path, always available)
// Implements Eq.14 (amplitude) + Eq.8 (phase) without speckle. 
class CpuComputeBackend : public SonarComputeBackend
{
public:
  const char * Name() const override { return "cpu"; }

  bool Initialize(const SonarComputeInput &) override { return true; }

  bool Compute(const SonarComputeInput & input,
               SonarComputeOutput & output) override
  {
    if (!input.depthImage || !input.normalImage || !input.reflectivityImage)
      return false;

    const int nb = input.nBeams;
    const int nr = input.nRays;
    const int nf = input.nFreq;

    output.nBeams = nb;
    output.nFreq  = nf;
    output.beamSpectrum.assign(
      static_cast<size_t>(nb) * nf, std::complex<float>(0.f, 0.f));

    const float c  = static_cast<float>(input.soundSpeed);
    const float B  = input.bandwidth;
    const float df = B / static_cast<float>(nf);
    const float pi = static_cast<float>(M_PI);

    auto t0 = std::chrono::high_resolution_clock::now();

    for (int b = 0; b < nb; ++b)
    {
      for (int ray = 0; ray < nr; ++ray)
      {
        if (ray >= input.depthImage->rows || b >= input.depthImage->cols)
          continue;

        const float r = input.depthImage->at<float>(ray, b);
        if (r <= 0.f || r > static_cast<float>(input.maxDistance))
          continue;

        const float mu = input.reflectivityImage->at<float>(ray, b);
        const cv::Vec3f n = input.normalImage->at<cv::Vec3f>(ray, b);

        // cos(α) approximation from surface normal
        const float cos_inc = std::abs(n[2]);

        // projected footprint: r^2 * dθ * dφ
        const float dth  = input.hFOV / std::max(nb - 1, 1);
        const float dphi = input.vFOV / std::max(nr - 1, 1);
        const float dA   = r * r * dth * dphi;

        // transmission loss (spreading + absorption)
        const float TL = std::exp(-static_cast<float>(input.attenuation) * r) / r;

        // Eq.14 amplitude
        const float A = std::sqrt(mu) * cos_inc * std::sqrt(dA) * TL;

        for (int f = 0; f < nf; ++f)
        {
          float freq;
          if (nf % 2 == 0)
            freq = df * (-static_cast<float>(nf) +
                         2.f * (static_cast<float>(f) + 1.f)) / 2.f;
          else
            freq = df * (-(static_cast<float>(nf) - 1.f) +
                          2.f * (static_cast<float>(f) + 1.f)) / 2.f;

          const float k   = 2.f * pi * freq / c;
          const float phi = 2.f * r * k;   // two-way path

          output.At(b, f) +=
            std::complex<float>(A * std::cos(phi), A * std::sin(phi));
        }
      }
    }

    auto t1 = std::chrono::high_resolution_clock::now();
    output.computeMicros =
      std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();

    return true;
  }
};


// Backend factory 
std::unique_ptr<SonarComputeBackend>
CreateComputeBackend(const std::string & name)
{
  if (name == "wgpu")
    return std::make_unique<WgpuComputeBackend>();

  // CUDA backend handled elsewhere
  return std::make_unique<CpuComputeBackend>();
}

// wgpu backend
const char * WgpuComputeBackend::Name() const { return "wgpu"; }

// Probe GPU once during init
bool WgpuComputeBackend::Initialize(const SonarComputeInput &)
{
#ifndef HAVE_WGPU_BACKEND
  std::cerr << "[sonar_wgpu] not compiled, using CPU.\n";
  gpuAvailable_ = false;
  initialized_  = true;
  return true;
#else
  void * probe = sonar_wgpu_create(
    1u, 1u, 4u,
    1500.f, 2950.f,
    10.f, 0.f,
    220.f, 1.f,
    1.5708f, 0.3491f,
    1u);

  if (probe)
  {
    sonar_wgpu_destroy(probe);
    gpuAvailable_ = true;
    std::cout << "[sonar_wgpu] GPU backend ready.\n";
  }
  else
  {
    gpuAvailable_ = false;
    std::cerr << "[sonar_wgpu] GPU unavailable, falling back to CPU.\n";
  }

  initialized_ = true;
  return true;
#endif
}


// Compute 
bool WgpuComputeBackend::Compute(
  const SonarComputeInput & input,
  SonarComputeOutput & output)
{
  if (!initialized_)
    return false;

  static void * engine = nullptr;
  static int e_nb = 0, e_nr = 0, e_nf = 0;

  // fallback path
  if (!engine)
  {
    gpuAvailable_ = false;

    if (!cpuFallback_){
        cpuFallback_ = std::make_unique<CpuComputeBackend>();
        cpuFallback_->Initialize(input);
    }

    return cpuFallback_->Compute(input, output);
  }

#ifndef HAVE_WGPU_BACKEND
  return false;
#else

  if (!input.depthImage || !input.normalImage || !input.reflectivityImage)
    return false;

  const int nb = input.nBeams;
  const int nr = input.nRays;
  const int nf = input.nFreq;

  auto t0 = std::chrono::high_resolution_clock::now();

  // flatten OpenCV layout → contiguous [beam * nr + ray]
  std::vector<float> depthFlat(nb * nr, 0.f);
  std::vector<float> reflFlat (nb * nr, 0.f);
  std::vector<float> normalFlat(nb * nr * 3, 0.f);

  for (int b = 0; b < nb; ++b)
  {
    for (int r = 0; r < nr; ++r)
    {
      if (r >= input.depthImage->rows || b >= input.depthImage->cols)
        continue;

      const size_t idx = static_cast<size_t>(b) * nr + r;

      depthFlat[idx] = input.depthImage->at<float>(r, b);
      reflFlat[idx]  = input.reflectivityImage->at<float>(r, b);

      const cv::Vec3f n = input.normalImage->at<cv::Vec3f>(r, b);
      normalFlat[idx*3+0] = n[0];
      normalFlat[idx*3+1] = n[1];
      normalFlat[idx*3+2] = n[2];
    }
  }

  // beam correction matrix (identity if missing)
  std::vector<float> beamCorrFlat(nb * nb, 0.f);
  if (input.beamCorrector)
  {
    for (int r = 0; r < nb; ++r)
      for (int c = 0; c < nb; ++c)
        beamCorrFlat[r * nb + c] = input.beamCorrector[r][c];
  }
  else
  {
    for (int i = 0; i < nb; ++i)
      beamCorrFlat[i * nb + i] = 1.f;
  }

  // persistent engine (recreated on dimension change)
  static void * engine = nullptr;
  static int    e_nb = 0, e_nr = 0, e_nf = 0;

  if (!engine || e_nb != nb || e_nr != nr || e_nf != nf)
  {
    if (engine)
      sonar_wgpu_destroy(engine);

    engine = sonar_wgpu_create(
      nb, nr, nf,
      input.soundSpeed,
      input.bandwidth,
      input.maxDistance,
      input.attenuation,
      input.sourceLevel,
      input.sensorGain,
      input.hFOV,
      input.vFOV,
      input.seed);

    e_nb = nb; e_nr = nr; e_nf = nf;

    if (!engine)
    {
      gpuAvailable_ = false;
      return Compute(input, output); // retry via CPU
    }
  }

  float * result = sonar_wgpu_compute(
    engine,
    depthFlat.data(),
    normalFlat.data(),
    reflFlat.data(),
    beamCorrFlat.data(),
    nb, nr, nf,
    input.frameIndex,
    input.beamCorrectorSum > 0.f ?
      input.beamCorrectorSum : static_cast<float>(nb));

  if (!result)
  {
    return Compute(input, output); // transient fallback
  }

  // unpack [re, im]
  output.nBeams = nb;
  output.nFreq  = nf;
  output.beamSpectrum.resize(nb * nf);

  for (int b = 0; b < nb; ++b)
  {
    for (int f = 0; f < nf; ++f)
    {
      const size_t i = (static_cast<size_t>(b) * nf + f) * 2;
      output.At(b, f) = { result[i], result[i + 1] };
    }
  }

  sonar_wgpu_free(result, nb * nf * 2);

  auto t1 = std::chrono::high_resolution_clock::now();
  output.computeMicros =
    std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();

  return true;
#endif
}

} // namespace sensors
} // namespace gz